name: Tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request: ~
  schedule:
    - cron: '0 0 * * *'

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.0', '8.1', '8.2', '8.3', '8.4', '8.5' ]
        stability: [ 'prefer-lowest', 'prefer-stable' ]
        database: [
          { distribution: 'mysql', version: '9.7' },
          { distribution: 'mysql', version: '8.4' },
          { distribution: 'mysql', version: '8.0' },
          { distribution: 'mysql', version: '5.7' },
          { distribution: 'mariadb', version: '12.2' },
          { distribution: 'mariadb', version: '11.8' },
          { distribution: 'mariadb', version: '11.4' },
          { distribution: 'mariadb', version: '10.11' },
          { distribution: 'mariadb', version: '10.6' },
          { distribution: 'mariadb', version: '10.5' }
        ]

    name: PHP ${{ matrix.php-versions }} / ${{ matrix.database.distribution }} ${{ matrix.database.version }} / ${{ matrix.stability }}

    continue-on-error: ${{ matrix.stability != 'prefer-stable' }}

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v6

      - name: 'Setup database'
        id: database
        uses: ./.github/actions/setup-database
        with:
          distribution: ${{ matrix.database.distribution }}
          version: ${{ matrix.database.version }}
          database: sakila

      - name: 'Install Sakila database'
        run: |
          mysql -uroot -h127.0.0.1 -P${{ steps.database.outputs.port }} < tests/Assets/Sakila/mysql-schema.sql
          mysql -uroot -h127.0.0.1 -P${{ steps.database.outputs.port }} < tests/Assets/Sakila/mysql-data.sql

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        env:
          # Temporary workaround while setup-php@v2 is still Node 20.
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: pdo, pdo-mysql
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: xdebug

      - name: 'Install dependencies'
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: 'Execute tests'
        env:
          MYSQL_DSN: ${{ steps.database.outputs.dsn }}
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
